### ISSUE TITLE
Create workflow editor

### ISSUE THREAD

**Issue by n-pola** [n-pola/can-i-cai#10]
Create the Workflow editor based on mockups and notes

![Editor - workflow failed](https://github.com/n-pola/can-i-cai/assets/56259168/dafa7b47-aaca-4835-95c3-f63ae851f340)

Depends on:
* [x] Create defined REST Endpoints #15
* [x] Create API requests frontend #20 
* [x] Create stores with required methods #33
* [x] Advance workflow rendering (positions, add buttons, edges, etc.) #43
* [x] Create Summary component #34
* [x] Create Tools component #35
* [x] Create basic modal component #36
* [x] Create confirm modal component #37
* [x] Create "Add component" modal component #38
* [x] Create "Add custom component" modal component #39
* [x] Create "Component detail" component #40
* [x] Create "Shared Workflow" modal component #41
* [x] Create local save and open logic #42
